name: C/C++ CI

on:
  push:
    branches:
    - '*'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
    - '*'

jobs:
  releaseBin:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.link_upload_url.outputs.upload_url }}

    steps:
    - name: Create Release
      if: ${{ contains(github.ref, 'refs/tags') }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{github.ref}}
        release_name: Release ${{github.ref}}
        draft: false
        prerelease: false
    - name: OutputUR
      id: link_upload_url
      run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"


  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [
          "codev_dp1000-v2_default",
        ]
    container:
      image: px4io/px4-dev-nuttx-focal:2021-04-29
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
    - name: ccache cache files
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: tests_${{matrix.ubuntu_release}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
        restore-keys: tests_${{matrix.ubuntu_release}}-ccache-
    - name: setup ccache
      run: |
          mkdir -p ~/.ccache
          echo "base_dir = ${GITHUB_WORKSPACE}" > ~/.ccache/ccache.conf
          echo "compression = true" >> ~/.ccache/ccache.conf
          echo "compression_level = 5" >> ~/.ccache/ccache.conf
          echo "max_size = 100M" >> ~/.ccache/ccache.conf
          ccache -s
          ccache -z
    - name: check environment
      run: |
          export
          ulimit -a

    - name: check_format
      run: make check_format

    - name: check_sitl
      run: make px4_sitl_default

    - name: ${{matrix.config}}
      run: make ${{matrix.config}}
    - name: upload coverage
      if: contains(matrix.check, 'coverage')
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        file: coverage/lcov.info

    - name: Create Version
      if: ${{ contains(github.ref, 'refs/tags') }}
      shell: bash
      run: |
        cd build/${{matrix.config}}/ &&\
        echo "##[set-output name=filename;]$(echo `ls`)" &&\
        echo "##[set-output name=version;]$(echo `ls`)"
      id: version

    - name: Upload Release Asset
      if: ${{ contains(github.ref, 'refs/tags') }}
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.releaseBin.outputs.upload_url }}
        asset_path: build/${{matrix.config}}/${{matrix.config}}.px4
        asset_name: ${{matrix.config}}.px4
        asset_content_type: application/zip
